# Generated by Django 2.2.19 on 2023-03-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230307_2342'),
    ]
    on_delete_action = django.db.models.deletion.SET_NULL
    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=on_delete_action,
                                    related_name='posts', to='posts.Group'),
        ),
    ]
